In [1]:
"""modelling 1 neuron with 4 input"""

inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1]
bias =2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias
print(output)

output=0
for i in range(0,len(inputs)):
    output = output + inputs[i]*weights[i]

print(output +bias)

4.8
4.8


In [3]:
"""modelling 3 neurons with 4 inputs

showcasing the output layer of NN"""

inputs = [1,2,3,2.5]
weights1 = [0.2,0.8,-0.5,1]
weights2 = [0.5,-0.91,0.26,-0.5]
weights3 = [-0.26,-0.27,0.17,0.87]

bias1 =2
bias2 =3
bias3 = 0.5

output = [
    inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
    inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
    inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3
]
print(output)

[4.8, 1.21, 2.385]


In [4]:
"""with loops"""
inputs = [1,2,3,2.5]

weights = [ [0.2,0.8,-0.5,1],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87] ]

biases = [2,3,0.5] 

layer_outputs = []

# result = zip(weights, biases)
# print(list(result))

for neuron_weight,neuron_bias in zip(weights, biases):
    neuron_output = 0
    for n_input,weight in zip(inputs, neuron_weight):
        neuron_output += n_input*weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)

print(layer_outputs)

[4.8, 1.21, 2.385]


In [6]:
# dot product
inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1]
bias = 2

import numpy as np

output = np.dot(inputs,weights) + bias
print(output)

4.8


In [5]:
import numpy as np

inputs = [1,2,3,2.5]

weights = [ [0.2,0.8,-0.5,1],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87] ]

biases = [2,3,0.5] 

# output = np.dot(inputs,weights) + biases # wont work --> ValueError: shapes (4,) and (3,4) not aligned: 4 (dim 0) != 3 (dim 0)
output = np.dot(weights,inputs) + biases
print(output)

[4.8   1.21  2.385]


In [7]:
np.random.seed(0)

"""showcasing Basic Relu"""

inputs = [0,2,-1,3.3, -2.7,1.1,2.2,-100]
output = []

for i in inputs:
    if i>0:
        output.append(i)
    else:
        output.append(0)

print(output)

output = []
for i in inputs:
    output.append(max(0,i))

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]
[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [8]:
import numpy as np 

np.random.seed(0)

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
#print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


In [9]:
"""Relu Activation """

import numpy as np
#pip install nnfs
#nnfs
import nnfs
from nnfs.datasets import spiral_data

# np.random.seed(0)
nnfs.init()     #sets defaults data type for using Numpy, as np.dot uses some other data type which creates complication further.

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

X,y = spiral_data(100,3)

# print(np.random.randn(2,4))


class Layer_Dense():
    def __init__(self, n_input, n_neurons) -> None:
        self.weights = 0.10 * np.random.randn(n_input, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights) + self.biases

class Activation_Relu():
    def forward(self, inputs) -> None:
        self.output =  np.maximum(0,inputs)

layer1 = Layer_Dense(2,5)
activation1 = Activation_Relu()
# layer2 = Layer_Dense(5,2)

layer1.forward(X)
print("Layer1.output",layer1.output)
activation1.forward(layer1.output)  # this should make all the -ve values in Layer1.output, zero
print(activation1.output)

# layer2.forward(layer1.output)
# print("Layer2.output",layer2.output)

Layer1.output [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-8.35815910e-04 -7.90404272e-04 -1.33452227e-03  4.65504505e-04
   4.56846210e-05]
 [-2.39994470e-03  5.93469958e-05 -2.24808278e-03  2.03573116e-04
   6.10024377e-04]
 ...
 [ 1.13291524e-01 -1.89262271e-01 -2.06855070e-02  8.11079666e-02
  -6.71350807e-02]
 [ 1.34588361e-01 -1.43197834e-01  3.09493970e-02  5.66337556e-02
  -6.29687458e-02]
 [ 1.07817926e-01 -2.00809643e-01 -3.37579325e-02  8.72561932e-02
  -6.81458861e-02]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+00 8.72561932e-02
  0

In [10]:
"""Basic python softmax activation"""

import math

layer_outputs = [4.8,1.21,2.385]
E = math.e

exp_values =[]

for output in layer_outputs:
    exp_values.append(math.pow(E,output))

#Expontiated values
print(exp_values)

# Normalization
norm_base = sum(exp_values)
norm_values =[]

for value in exp_values:
    norm_values.append(value/norm_base)

print(norm_values)
print(sum(norm_values))

[121.51041751873483, 3.353484652549023, 10.859062664920513]
[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]
0.9999999999999999


In [11]:
"""Basic Numpy softmax activation"""

import numpy as np

layer_outputs = [4.8,1.21,2.385]

exp_values =[]
exp_values = np.exp(layer_outputs)

#Expontiated values
print(exp_values)

# Normalization
norm_values =[]
norm_values = exp_values / np.sum(exp_values)

print(norm_values)
print(np.sum(norm_values))

[121.51041752   3.35348465  10.85906266]
[0.89528266 0.02470831 0.08000903]
0.9999999999999999


In [22]:
arr = [[4.8,1.21,2.385],
       [8.9,-1.81,0.2],
       [1.41,1.051,0.026]]

print(np.sum(arr))
print(np.sum(arr, axis=None))

print(np.sum(arr, axis=0))   # Column wise sum
print(np.sum(arr, axis=1))    # Row  wise sum

# If keepdims is set to True, the axes which are reduced are left in the result as dimensions with size one.
# With this option, the result will broadcast correctly against the input array.
print(np.sum(arr, axis=1, keepdims=True))  

18.172
18.172
[15.11   0.451  2.611]
[8.395 7.29  2.487]
[[8.395]
 [7.29 ]
 [2.487]]


In [12]:
layer_outputs = [[4.8,1.21,2.385],
       [8.9,-1.81,0.2],
       [1.41,1.051,0.026]]

exp_values = np.exp(layer_outputs)

In [13]:
import numpy as np

layer_outputs = [[4.8,1.21,2.385],
       [8.9,-1.81,0.2],
       [1.41,1.051,0.026]]

exp_values = np.exp(layer_outputs)

 # does not give true normalized value, as it is taking sum of the entire outputs rather than 1 output 
norm_values = exp_values / np.sum(exp_values) 
print(norm_values)

norm_values = exp_values / np.sum(exp_values,axis=1, keepdims=True)
print(norm_values)

[[1.62510862e-02 4.48502847e-04 1.45231633e-03]
 [9.80595215e-01 2.18874853e-05 1.63353249e-04]
 [5.47802614e-04 3.82571295e-04 1.37265228e-04]]
[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


In [25]:
"""showcasing  Relu and softmax activations object"""

import numpy as np
import nnfs
from nnfs.datasets import spiral_data

np.random.seed(0)
nnfs.init()     #sets defaults data type for using Numpy, as np.dot uses some other data type which creates complication further.

X,y = spiral_data(samples =100,classes= 3)

class Layer_Dense():
    def __init__(self, n_input, n_neurons) -> None:
        self.weights = 0.10 * np.random.randn(n_input, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights) + self.biases

class Activation_Relu():
    def forward(self, inputs) -> None:
        self.output =  np.maximum(0,inputs)

class Activation_Softmax():
    def forward(self,inputs):
        exp_values = np.exp(inputs-np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities    

dense1 = Layer_Dense(2,3)
activation1 = Activation_Relu()
dense2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)  # this should make all the -ve values in dense.output, zero

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])  #5 rows


[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]


The distirbution of prediction is close to perfect 1/3rd.

What is logarithm ?

--> solving for x  
e**x = b , wher e is euler's number

In [14]:
b=5.2
print(np.log(b))

1.6486586255873816


In [30]:
print(math.e**1.6486586255873816)

5.199999999999999


Calculating loss with catgorical cross entropy

In [33]:
import math

softmax_output = [0.7,0.1,0.2]    #sum equals 1
# target_class = 0   # vector is hot at index 0
target_output =[1,0,0]

loss = -(target_output[0]*math.log(softmax_output[0]) +
            target_output[1]*math.log(softmax_output[1]) +
            target_output[2]*math.log(softmax_output[2]))
                                      
print(loss)                                                                

0.35667494393873245


In [34]:
loss = -(target_output[0]*math.log(softmax_output[0]))
print(loss)

0.35667494393873245


In [37]:
print(-math.log(softmax_output[0]))

0.35667494393873245


In [36]:
print(-math.log(0.7))
print(-math.log(0.5))

0.35667494393873245
0.6931471805599453


in [36] we can see as the confidence was higher in correct class the loss is lower.  
And where the condifence in the correct class gets lower the loss( measurement of error) gets higher.

In [ ]:
"""Batch processing"""
import numpy as np

softmax_outputs = np.array([[0.7,0.1,0.2],
                            [0.1,0.5,0.4],
                            [0.02,0.9,0.08]])
class_targets =[0,1,1]

print(softmax_outputs[[0,1,2],class_targets])
print(softmax_outputs[[0,1,2],0])

print(np.mean(-np.log(softmax_outputs[[0,1,2],class_targets])))

In [41]:
print(1-1e-7)

0.9999999


## Incorporate Categorical loss entropy in the running example

In [15]:
import numpy as np

import nnfs
from nnfs.datasets import spiral_data

np.random.seed(0)
nnfs.init()     #sets defaults data type for using Numpy, as np.dot uses some other data type which creates complication further.

X,y = spiral_data(samples =100,classes= 3)

class Layer_Dense():
    def __init__(self, n_input, n_neurons) -> None:
        self.weights = 0.10 * np.random.randn(n_input, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights) + self.biases

class Activation_Relu():
    def forward(self, inputs) -> None:
        self.output =  np.maximum(0,inputs)

class Activation_Softmax():
    def forward(self,inputs):
        exp_values = np.exp(inputs-np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities    

class Loss():
    def calculate(self, output, y):
        sample_losses = self.forward(output,y)
        data_loss = np.mean(sample_losses)
        return data_loss
    
class Loss_CategoricalCrossEntropy(Loss):
    def forward(self, y_pred, y_true):
        samples =len(y_pred)
        y_pred_clipped =np.clip(y_pred,1e-7, 1-1e-7)  # to avoid memory overflow due to exponentiation
        
        if len(y_true.shape)==1:   #checks for scalar values
            correct_confidences = y_pred_clipped[range(samples),y_true]
        elif len(y_true.shape) ==2:  #1 hot encoded vector being passed
            correct_confidences= np.sum(y_pred_clipped*y_true,axis=1)
        
        negative_log_liklihoods = -np.log(correct_confidences)
        return negative_log_liklihoods
    
dense1 = Layer_Dense(2,3)
activation1 = Activation_Relu()
dense2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)  # this should make all the -ve values in dense.output, zero

dense2.forward(activation1.output)
activation2.forward(dense2.output)

# print(activation2.output[:5])  #5 rows
loss_function = Loss_CategoricalCrossEntropy()
loss = loss_function.calculate(activation2.output,y)

print("Loss:", loss)

# Accuracy calculation
predictions =np.argmax(activation2.output, axis=1)
accuracy = np.mean(predictions == y)
print("acc: ", accuracy)


Loss: 1.098445
acc:  0.34


In [20]:
import matplotlib.pyplot as plt
import nnfs
from nnfs.datasets import vertical_data

nnfs.init()

X,y = vertical_data(samples=100, classes=3)

In [45]:
# plt.scatter(X[:,0], X[:,1], c=y, s=40, cmap='brg')
# plt.show()

print(np.ndim(X))
print(np.shape(X))
print(np.shape(np.zeros((2, 3))))

2
(300, 2)
(2, 3)


In [46]:
# Object instantiation
dense1 = Layer_Dense(2,3)
activation1 = Activation_Relu()

dense2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()

loss_function = Loss_CategoricalCrossEntropy()

lowest_loss = 999999
best_dense1_weights = dense1.weights.copy()
best_dense1_biases = dense1.biases.copy()
best_dense2_weights = dense2.weights.copy()
best_dense2_biases = dense2.biases.copy()

for iteration in range(100000):   #epochs
    dense1.weights = 0.5* np.random.randn(2,3)
    dense1.biases =  0.5* np.random.randn(1,3)
    dense2.weights = 0.5* np.random.randn(3,3)
    dense2.biases = 0.5* np.random.randn(1,3)

    dense1.forward(X)
    activation1.forward(dense1.output)
    dense2.forward(activation1.output)
    activation2.forward(dense2.output)

    loss = loss_function.calculate(activation2.output,y)

    predictions = np.argmax(activation2.output, axis=1)
    accuracy = np.mean(predictions == y)

    if loss < lowest_loss:
        print('New set of weights found, iteration:', iteration, 'loss:', loss, 'acc:',accuracy)
        best_dense1_weights = dense1.weights.copy()
        best_dense1_biases = dense1.biases.copy()
        best_dense2_weights = dense2.weights.copy()
        best_dense2_biases = dense2.biases.copy()
        lowest_loss = loss
        

New set of weights found, iteration: 0 loss: 1.1528968 acc: 0.31333333333333335
New set of weights found, iteration: 1 loss: 1.1461446 acc: 0.3333333333333333
New set of weights found, iteration: 2 loss: 1.1053249 acc: 0.38333333333333336
New set of weights found, iteration: 21 loss: 1.1035887 acc: 0.3333333333333333
New set of weights found, iteration: 25 loss: 1.100974 acc: 0.3333333333333333
New set of weights found, iteration: 36 loss: 1.052621 acc: 0.6633333333333333
New set of weights found, iteration: 96 loss: 1.0261556 acc: 0.37
New set of weights found, iteration: 373 loss: 1.0092345 acc: 0.62
New set of weights found, iteration: 395 loss: 0.97559196 acc: 0.48333333333333334
New set of weights found, iteration: 1512 loss: 0.97331667 acc: 0.45666666666666667
New set of weights found, iteration: 9281 loss: 0.959499 acc: 0.55
New set of weights found, iteration: 10815 loss: 0.9367594 acc: 0.66
New set of weights found, iteration: 11888 loss: 0.9353194 acc: 0.61
New set of weights